//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hua_bbs.Web.Reply {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblt_t_id;
	protected global::System.Web.UI.WebControls.Label lblt_u_id;
		protected global::System.Web.UI.WebControls.TextBox txtmodifytime;
		protected global::System.Web.UI.WebControls.TextBox txtpublishtime;
		protected global::System.Web.UI.WebControls.TextBox txtcontent;
		protected global::System.Web.UI.WebControls.TextBox txttitle;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
