//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hua_bbs.Web.Topic {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblt_u_id;
	protected global::System.Web.UI.WebControls.Label lblt_s_id;
	protected global::System.Web.UI.WebControls.Label lblcontent;
	protected global::System.Web.UI.WebControls.Label lblmodifytime;
	protected global::System.Web.UI.WebControls.Label lblpublishtime;
	protected global::System.Web.UI.WebControls.Label lbltitle;
	protected global::System.Web.UI.WebControls.Label lblgood;
	protected global::System.Web.UI.WebControls.Label lbltop;


       
    }
}
