//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hua_bbs.Web.User {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtemail;
		protected global::System.Web.UI.WebControls.TextBox txtface;
		protected global::System.Web.UI.WebControls.TextBox txtmobile;
	protected global::System.Web.UI.WebControls.Label lblnickname;
		protected global::System.Web.UI.WebControls.TextBox txtpassword;
		protected global::System.Web.UI.WebControls.TextBox txtregtime;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txttruename;
		protected global::System.Web.UI.WebControls.TextBox txttype;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
